config/routes.rb
Rails.application.routes.draw do

  root to: "colleges#index"

  get "/register", to: "users#new"
  resources :users, only: [:create] do
    member do
      get 'join_college', to: "users#get_join_college"
      patch 'save_college', to: "users#join_college"
    end
  end

  get "/sign_in", to: "sessions#new"
  delete "/sign_out", to: 'sessions#destroy'
  resources :sessions, only: [:create] 

  get 'auth/:provider/callback', to: 'sessions#facebook_create'
  get 'auth/failure', to: redirect('/')

  resources :colleges, path: '/', only: [:show] do
    resources :users, only: [:edit, :update] do
      get '/my-books', to: 'books#my_books'
      get "/inbox", to: "messages#inbox"
      get "thread/:id", to: "messages#thread", as: 'thread'
      
    end
    resources :categories, only: [:show]
    
    resources :books do
      member do
        post 'message', to: 'messages#create'
      end
    end
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :reciever, class_name: "User", foreign_key: "reciever_id"
  belongs_to :book

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    @book = Book.find(params[:id])
    @message = Message.new(sender: current_user, reciever: @book.user, book: @book, text: params[:message][:text])
    if @message.save
      flash[:success] = "Your message has been sent."
      redirect_to college_user_inbox_path(current_college, current_user)
    else
      render 'books/show'
    end
  end

  def inbox
    @messages_array = current_user.ordered_message_threads
  end

  def thread
    @message = Message.new
    leading_msg = Message.find(params[:id])
    @thread = Message.where("(sender_id = #{current_user.id} or reciever_id = #{current_user.id}) and (sender_id = #{current_user.other_guy(leading_msg).id} or reciever_id = #{current_user.other_guy(leading_msg).id}) and book_id = #{leading_msg.book.id}").order("created_at DESC")
    @thread.each do |msg|
      if msg.viewed.nil?
        msg.viewed = true;
        msg.save
      end
    end
  end

end

app/views/messages/inbox.html.haml
%br
.textbook-titles
  .red= current_user.name
  .dark-blue Mailbox


- if @messages_array.any?
  .messages-container
    - @messages_array.each do |sub_array|
      = link_to college_user_thread_path(current_college,current_user,sub_array.first), class: "msg-box #{(sub_array.first.viewed ? 'viewed' : 'unviewed')}" do
        .other-guy= "#{current_user.other_guy(sub_array.first).name} (#{sub_array.size})"
        .text= truncate(sub_array.first.text, 40)
        .time= sub_array.first.created_at.strftime("%d %b. %Y")
        - if current_user.other_guy(sub_array.first).profile_images.any?
          = image_tag current_user.other_guy(sub_array.first).profile_images.last.profile_image_url(:mobile).to_s, class: "square-propic"
        - else
          = image_tag "/no-user.png", class: "square-propic"

  / .msg-box 
  /   .text I'm wondering about the books condition compared to the
  /   .other-guy Tayron lyn
  /   - if current_user.profile_images.any?
  /     = image_tag current_user.profile_images.last.profile_image_url(:mobile).to_s, class: "square-propic"
  /   - else
  /     = image_tag "/no-user.png", class: "square-propic"
  /   .time January 5 2105

  / .msg-box
  /   .text I'm wondering about the books condition compared to the
  /   .other-guy Etoboii
  /   - if current_user.profile_images.any?
  /     = image_tag current_user.profile_images.last.profile_image_url(:mobile).to_s, class: "square-propic"
  /   - else
  /     = image_tag "/no-user.png", class: "square-propic"
  /   .time January 5 2105

app/views/messages/thread.html.haml
%br
.textbook-titles
  .red= Message
  .dark-blue Thread

.textbook-titles
  .black.textbook-thread= "For: #{@thread.first.book.title}"

= link_to college_user_inbox_path(current_college, current_user), class: "back-inbox" do
  %i.fa.fa-inbox


.messages-container
  - @thread.each do |msg|
    .msg-box
      - if msg.sender.profile_images.any?
        = image_tag msg.sender.profile_images.last.profile_image_url(:mobile).to_s, class: "square-propic"
      - else
        = image_tag "/no-user.png", class: "square-propic"
      .info-container
        .other-guy= "#{msg.sender.name}"
        .text= msg.text
        .time= msg.created_at.strftime("%d %b. %Y")




- if @message.errors.any?
  %ul
    - @message.errors.full_messages.each do |msg|
      %li= msg
.signUpForm.brown-background
  = form_for @message, url: message_college_book_path(current_college, @thread.first.book), html: { class: 'flp'} do |f|

    .input-group
      = f.text_area :text, id: "exText", class: "form-control", placeholder: "Send a message to #{current_user.other_guy(@thread.first).name}"
      .input-group-addon
        %i.fa.fa-pencil

    %button#loading-example-btn.btn.btn-register.btn-block.blue-submit{"data-loading-text" => "Logining in...", :type => "submit"} Send
    <hr/>