config/routes.rb
Rails.application.routes.draw do

  root to: "colleges#index"

  get "/register", to: "users#new"
  resources :users, only: [:create] do
    member do
      get 'join_college', to: "users#get_join_college"
      patch 'save_college', to: "users#join_college"
    end
  end

  get "/sign_in", to: "sessions#new"
  delete "/sign_out", to: 'sessions#destroy'
  resources :sessions, only: [:create] 

  get 'auth/:provider/callback', to: 'sessions#facebook_create'
  get 'auth/failure', to: redirect('/')

  resources :colleges, path: '/', only: [:show] do
    resources :users, only: [:edit, :update] do
      get '/my-books', to: 'books#my_books'
      get "/inbox", to: "messages#inbox"
      get "thread/:id", to: "messages#thread", as: 'thread'
      
    end
    resources :categories, only: [:show]
    
    resources :books do
      member do
        post 'message', to: 'messages#create'
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password :validations => false
  has_many :books, dependent: :destroy
  has_many :profile_images
  has_many :sent, class_name: "Message", foreign_key: "sender_id"
  has_many :recieved, class_name: "Message", foreign_key: "reciever_id"  
  belongs_to :college
  # has_many :sent_proposals, class_name: "Proposal", foreign_key: "sender_id"
  # has_many :recieved_proposals, class_name: "Proposal", foreign_key: "reciever_id"

  validates :name, presence: true
  validates :email_address, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :password, presence: true, length: { maximum: 20 }, if: :user_validations_needed?
 


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider 
      user.uid      = auth.uid
      user.name     = auth.info.name
      user.email_address = auth.info.email
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save
    end
  end

  def in_college?
    return !!college
  end

  def user_validations_needed?
    if created_at.nil? && provider.nil?
      return true
    else
      return false
    end
  end

# --------------------- Messages --------------------------------------------------

  def ordered_message_threads
    bin = []
    my_messages = gather_my_messages
    my_messages.sort_by(&:created_at).each do |msg|
      if !bin.flatten.include?(msg)
        sub_bin = Message.where("(sender_id = #{self.id} or reciever_id = #{self.id}) and (sender_id = #{other_guy(msg).id} or reciever_id = #{other_guy(msg).id}) and book_id = #{msg.book.id}").order("created_at DESC")
        bin << sub_bin
      end
    end
    return bin
  end

  def gather_my_messages
    my_messages = []
    my_messages << self.sent
    my_messages << self.recieved
    return my_messages.flatten!
  end

  def other_guy(message)
    if message.sender == self
      return message.reciever
    else
      return message.sender
    end
  end

 # ---------------------------------- PRoposals --------------------------------------------
  # def unique_recieved_proposals
  #   dropbox = []
  #   recieved_proposals.where(reciever_confirmation: nil).each do |proposal|
  #     if unique_proposal?(proposal) && proposal == latest_proposal_of_this_book_related_to_me_and_my_guy(other_guy(proposal), proposal.book)
  #       dropbox << proposal
  #     end
  #   end
  #   return dropbox
  # end


  # def recieved_change_proposals
  #   dropbox = []
  #   recieved_proposals.where(reciever_confirmation: nil).each do |proposal|
  #     if !unique_proposal?(proposal) && proposal == latest_proposal_of_this_book_related_to_me_and_my_guy(other_guy(proposal), proposal.book)
  #       dropbox << proposal
  #     end
  #   end
  #   return dropbox    
  # end

  # def confirmed_proposals
  #   dropbox = []
  #   my_proposals.where(reciever_confirmation: true).each do |accepted_proposal|
  #     if accepted_proposal == latest_proposal_of_this_book_related_to_me_and_my_guy(other_guy(accepted_proposal), accepted_proposal.book)
  #       dropbox << accepted_proposal
  #     end
  #   end
  #   return dropbox
  # end

  # def pending_sent_proposals
  #   dropbox = []
  #   sent_proposals.where(reciever_confirmation: nil).each do |sent_proposal|
  #     dropbox << sent_proposal if sent_proposal == latest_proposal_of_this_book_related_to_me_and_my_guy(other_guy(sent_proposal), sent_proposal.book)
  #   end
  #   return dropbox
  # end


  # # returns other guy in proposal who is not current user
  # def other_guy(proposal)
  #   if proposal.reciever != self
  #     return proposal.reciever
  #   else
  #     return proposal.sender
  #   end
  # end

  # def all_proposals_of_this_book_for_me_and_this_guy(other_guy, book)
  #   Proposal.where("(reciever_id = #{self.id} or sender_id = #{self.id}) and (reciever_id = #{other_guy.id} or sender_id = #{other_guy.id}) and book_id = #{book.id}")
  # end

  # private # ------------------------------------------

  # # when using this method, make sure other guy is for sure not current user
  # def latest_proposal_of_this_book_related_to_me_and_my_guy(other_guy, book)
  #   Proposal.where("(reciever_id = #{self.id} or sender_id = #{self.id}) and (reciever_id = #{other_guy.id} or sender_id = #{other_guy.id}) and book_id = #{book.id}").last
  # end




  # # all my sent and recieved proposals
  # def my_proposals
  #   Proposal.where("(reciever_id = #{id}) or sender_id = #{id}")
  # end

  # # returns false if both users have sent each other a proposal for certain book, else returns true if only one user had sent a proposal
  # def unique_proposal?(proposal)
  #   if Proposal.where("((reciever_id = #{self.id}) and sender_id = #{other_guy(proposal).id}) and book_id = #{proposal.book_id}").any? && Proposal.where("((reciever_id = #{other_guy(proposal).id}) and sender_id = #{self.id}) and book_id = #{proposal.book_id}").any? 
  #     return false
  #   else
  #     return true
  #   end
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:edit, :update, :get_join_college, :join_college]
  before_action :current_user_must_be_owner, only: [:edit, :update, :get_join_college, :join_college]
  before_action :must_be_logged_out, only: [:home]
  before_action :no_college_member_users, only: [:get_join_college, :join_college]

  def home
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Welcome you are now a registered member!"
      redirect_to sign_in_path
    else
      render :new
    end
  end

  def edit
  
  end

  def update
    @user = current_user
    if @user.update_attributes(update_user_params)
      if params[:profile_images]
        params[:profile_images].each { |image|
          @user.profile_images.create(profile_image: image)
        }
      end
      flash[:success] = "Your changes have been saved."
      redirect_to edit_college_user_path(current_college, @user)
    else
      render :edit
    end
  end

  def get_join_college
    @user = User.find(params[:id])
  end

  def join_college
    college = College.find(params[:user][:college_id])
    user = current_user
    if user.update_attribute('college_id', college.id)
      flash[:success] = "You are registered as a #{college.name} student!"
      redirect_to college_path(college)
    else
      flash[:error] = "There was an error."
      render :get_join_college
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email_address, :password)
  end

  def update_user_params
    if params[:user][:password] == ""
      return params.require(:user).permit(:name, :email_address)
    else
      return params.require(:user).permit(:name, :email_address, :password, :profile_image)
    end
  end

  def current_user_must_be_owner
    if User.find(params[:id]) != current_user
      redirect_to (current_college ? college_path(current_college): root_path) 
    end
  end

  def no_college_member_users
    redirect_to college_path(current_college) unless current_user.college.nil?
  end
end

app/views/users/edit.html.haml
- if current_user.errors.any?
  %ul
    - current_user.errors.full_messages.each do |msg|
      %li= msg
.signUpForm
  = form_for [current_user.college, current_user], html: { multipart: true, class: 'flp'} do |f|

    = file_field_tag "profile_images[]", multiple: true, type: :file, id: "edit-file", class: "form-file"
    %label{:for => "edit-file"}
      %span.fa.fa-upload Upoad Pro-pic

    .input-group
      = f.text_field :name, id: "exEmail", class: "form-control", placeholder: "Full Name"
      .input-group-addon
        %i.fa.fa-user
    .input-group.has-feedback
      = f.email_field :email_address, id: "exEmail", class: "form-control", placeholder: "Email"
      .input-group-addon
        %i.fa.fa-envelope
    .input-group
      = f.password_field :password, id: "exPassword", class: "form-control", placeholder: "Password"
      .input-group-addon
        %i.fa.fa-lock
    %button#loading-example-btn.btn.btn-register.btn-block{"data-loading-text" => "Logining in...", :type => "submit"} Save Changes

.bottom-half-container
  .description= "Student at #{current_user.college.name}"
  - if current_user.profile_images.any?
    = image_tag current_user.profile_images.last.profile_image_url(:mobile).to_s, class: "profile-circle"
  - else
    = image_tag "/no-user.png", class: "profile-circle"

app/views/users/get_join_college.html.haml
 
- if @user.errors.any?
  %ul
    - @user.errors.full_messages.each do |msg|
      %li= msg
.signUpForm
  = form_for @user, url: save_college_user_path(@user), html: { class: 'flp'} do |f|

    .radio-class-container
      .radio-grp
        %h4.title Select your College
        = f.collection_radio_buttons(:college_id, College.all, :id, :name, multipart: false) do |b|
          .radio-btn
            = b.radio_button
            = b.label(for: "user_college_id_#{b.object.id}", class: "textbook")

    %button#loading-example-btn.btn.btn-register.btn-block{"data-loading-text" => "Logining in...", :type => "submit"} Join
    <hr/>

app/views/users/home.html.haml
%div.homepage-jumbotron
  %h3.gw GW
  %h3.book-market BOOK MARKET

  = link_to('/auth/facebook', class: "facebook-link") do
    = image_tag "/fb-login.png"

  = link_to "Sign in", sign_in_path, class: "login-link"

  .register-question
    Create a new account 
    = link_to "here", register_path

%h3.category-title Textbooks

.category-container 
  = link_to(category_path(2), class: "home-category-link") do
    %i.fa.fa-rocket.icon
    %h4.category-name Physics
  = link_to(category_path(3), class: "home-category-link") do
    %i.fa.fa-globe.icon
    %h4.category-name Biology
  = link_to(category_path(4), class: "home-category-link") do
    %i.fa.fa-plus.icon
    %h4.category-name Calculus
  = link_to(category_path(5), class: "home-category-link") do
    %i.fa.fa-money.icon
    %h4.category-name Economics
  = link_to(category_path(6), class: "home-category-link") do
    %i.fa.fa-flask.icon
    %h4.category-name Chemistry
  = link_to(category_path(7), class: "home-category-link") do
    %i.fa.fa-spinner.icon
    %h4.category-name Other

.info-container 
  This is the place for GW students to sell and buy or swap their textbooks with other students from GW. Simple, Efficient and Fast.

app/views/users/new.html.haml
- if @user.errors.any?
  %ul
    - @user.errors.full_messages.each do |msg|
      %li= msg
.signUpForm
  = form_for @user, html: { class: 'flp'} do |f|
    .input-group
      = f.text_field :name, id: "exEmail", class: "form-control", placeholder: "Full Name"
      .input-group-addon
        %i.fa.fa-user
    .input-group.has-feedback
      = f.email_field :email_address, id: "exEmail", class: "form-control", placeholder: "Email"
      .input-group-addon
        %i.fa.fa-envelope
    .input-group
      = f.password_field :password, id: "exPassword", class: "form-control", placeholder: "Password"
      .input-group-addon
        %i.fa.fa-lock
    %button#loading-example-btn.btn.btn-register.btn-block{"data-loading-text" => "Logining in...", :type => "submit"} Register
    <hr/>
    = link_to('/auth/facebook', class: "facebook-link-register") do
      = image_tag "/facebook-register.png"