config/routes.rb
Rails.application.routes.draw do

  root to: "colleges#index"

  get "/register", to: "users#new"
  resources :users, only: [:create] do
    member do
      get 'join_college', to: "users#get_join_college"
      patch 'save_college', to: "users#join_college"
    end
  end

  get "/sign_in", to: "sessions#new"
  delete "/sign_out", to: 'sessions#destroy'
  resources :sessions, only: [:create] 

  get 'auth/:provider/callback', to: 'sessions#facebook_create'
  get 'auth/failure', to: redirect('/')

  resources :colleges, path: '/', only: [:show] do
    resources :users, only: [:edit, :update] do
      get '/my-books', to: 'books#my_books'
      get "/inbox", to: "messages#inbox"
      get "thread/:id", to: "messages#thread", as: 'thread'
      
    end
    resources :categories, only: [:show]
    
    resources :books do
      member do
        post 'message', to: 'messages#create'
      end
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @books = Book.where(category: @category, college: current_college).order("created_at DESC").page(params[:page]).per(15)
  end

end

app/views/categories/show.html.haml
%br
.textbook-titles
  .red= @category.name
  .blue Textbooks
  - if logged_in?
    .post-buttons
      = link_to new_college_book_path(current_college), class: "post-button" do
        %i.fa.fa-pencil-square-o.blue-icon
        %p Post

- @books.each do |book|
  = link_to college_book_path(current_college,book), class: "category-book" do 
    .info
      %h3= truncate(book.title, 25)
      .swap 
        Seller:
        %span= book.user.name
      .swap 
        %span= book.created_at.strftime("%d %b. %Y")
      .show-icon-info
        .block-info 
          %i.fa.fa-usd
          %span= book.price
        .block-info
          %i.fa.fa-gavel
          %span= book.condition
        .block-info
          %i.fa.fa-book
          %span= book.category.name
    - if book.images.any?
      .textbook-image{:style => "background-image: url(#{book.images.first.image_url(:mobile).to_s});"}
    - else
      .textbook-image{:style => "background-image: url('/no_image.jpg');"}  

    - if book.user.profile_images.any?
      = image_tag book.user.profile_images.last.profile_image_url(:mobile).to_s, class: "profile-circle"
    - else
      = image_tag "/no-user.png", class: "profile-circle"
    

.pagination-container
  = paginate @books