config/routes.rb
Rails.application.routes.draw do

  root to: "colleges#index"

  get "/register", to: "users#new"
  resources :users, only: [:create] do
    member do
      get 'join_college', to: "users#get_join_college"
      patch 'save_college', to: "users#join_college"
    end
  end

  get "/sign_in", to: "sessions#new"
  delete "/sign_out", to: 'sessions#destroy'
  resources :sessions, only: [:create] 

  get 'auth/:provider/callback', to: 'sessions#facebook_create'
  get 'auth/failure', to: redirect('/')

  resources :colleges, path: '/', only: [:show] do
    resources :users, only: [:edit, :update] do
      get '/my-books', to: 'books#my_books'
      get "/inbox", to: "messages#inbox"
      get "thread/:id", to: "messages#thread", as: 'thread'
      
    end
    resources :categories, only: [:show]
    
    resources :books do
      member do
        post 'message', to: 'messages#create'
      end
    end
  end

end

app/views/layouts/_flash.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    - if name == 'success'
      .flash.clickhide.alert.alert-success.alert-dismissable{:role => "alert"}
        %button.close{"data-dismiss" => "alert", :type => "button"}
          %span{"aria-hidden" => "true"}
          %span.sr-only Close
        %p.lead= msg
    - elsif name == 'error'
      .flash.clickhide.alert.alert-danger.alert-dismissable{:role => "alert"}
        %button.close{"data-dismiss" => "alert", :type => "button"}
          %span{"aria-hidden" => "true"}
          %span.sr-only Close
        %p.lead= msg

app/views/layouts/_footer.html.haml
%footer#footer © Trink-it 2015

app/views/layouts/_my_menu.html.haml
%nav#my-menu
  %ul.mm-border-none
    - if logged_in? 
      %li.gray-sign-in
        = link_to sign_out_path, method: "delete" do
          %i.fa.fa-power-off.purple-icon
          %p Log out
      %li
        - if current_user.in_college?
          = link_to college_user_my_books_path(current_college, current_user) do
            %i.fa.fa-bookmark.green-icon
            %p My Books
          %li
            = link_to edit_college_user_path(current_college, current_user) do
              %i.fa.fa-user
              %p Account
          %li
            = link_to new_college_book_path(current_college) do
              %i.fa.fa-pencil-square-o.blue-icon
              %p Post textbook
        - else
          = link_to join_college_user_path(current_user) do
            %i.fa.fa-building.green-icon
            %p Join College
    - if !logged_in?
      %li.gray-sign-in
        = link_to sign_in_path do
          %i.fa.fa-power-off.purple-icon
          %p Sign in
        %li
          = link_to register_path do
            %i.fa.fa-building.green-icon
            %p Register

    - if college_present?
      %li
        = link_to '#' do
          %i.fa.fa-book
          %p Textbooks
        %ul
          %br
          .category-container 
            = link_to(college_category_path(current_college,4), class: "home-category-link") do
              %i.fa.fa-rocket.icon
              %h4.category-name Physics
            = link_to(college_category_path(current_college,3), class: "home-category-link") do
              %i.fa.fa-globe.icon
              %h4.category-name Biology
            = link_to(college_category_path(current_college,1), class: "home-category-link") do
              %i.fa.fa-flask.icon
              %h4.category-name Chemistry
            = link_to(college_category_path(current_college,2), class: "home-category-link") do
              %i.fa.fa-plus.icon
              %h4.category-name Culculus
            = link_to(college_category_path(current_college,5), class: "home-category-link") do
              %i.fa.fa-money.icon
              %h4.category-name Economics
            = link_to(college_category_path(current_college,7), class: "home-category-link") do
              %i.fa.fa-frown-o.icon
              %h4.category-name Psychology
            = link_to(college_category_path(current_college,8), class: "home-category-link") do
              %i.fa.fa-pie-chart.icon
              %h4.category-name Statistics
            = link_to(college_category_path(current_college,6), class: "home-category-link") do
              %i.fa.fa-spinner.icon
              %h4.category-name Other

app/views/layouts/_navbar.html.haml
%nav.navbar.trinkit-navbar
  - if current_college || @college
    = link_to college_path((@college ? @college : current_college)), class: "logo" do
      Trink-it
      %span.green= abreviate((@college ? @college.name : current_college.name))
  - else
    = link_to "Trink-it", root_path, class: "logo"
  %a.bar.icon-link{:href => "#my-menu"}
    %i.fa.fa-bars

app/views/layouts/application.html.haml
!!! 5
%html(lang="en-US")
  %head
    %title Trinket
    %meta(charset="UTF-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = csrf_meta_tag
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
  %body
    = render 'layouts/my_menu'
    
    %div.main-content
      = render 'layouts/navbar'
      = render 'layouts/flash'
      = yield
    = render 'layouts/footer'